### ISSUE TITLE
Update to latest rand

### ISSUE THREAD

**Issue by opoplawski** [ejmahler/rust_dct#12]
It would be very helpful for Fedora packaging purposes if rust_dct updated it's rand usage to 0.8.  There are quite a lot of API changes though that I can't sort out - particularly as a non-Rust programmer.  Thank you for your consideration.

**Comment by ejmahler** [comment]
This was done in release 0.7.1. Thanks for bringing this up!

**Comment by opoplawski** [comment]
Thank you
