### ISSUE TITLE
Update `rustfft` version

### ISSUE THREAD

**Issue by ksesong** [ejmahler/rust_dct#3]
Would it be possible to update the `rustfft` version to `3.0.0` as the current one depends on `num-complex@0.1.43` which uses `rustc-serialize` which is deprecated (and can't be compiled to `wasm` targets). The new version no longer uses `rustc-serialize` but there might be some breaking changes to account for.

**Comment by ejmahler** [comment]
Done https://crates.io/crates/rustdct/0.4.0
