### ISSUE TITLE
Accept oversize scratch slices

### ISSUE THREAD

**Issue by millardjn** [ejmahler/rust_dct#9]
Hello

Currently scratch lengths are checked within the library as `assert_eq!(scratch.len(), self.get_scratch_len())` and this caught me out when reusing a scratch for DCTs of various lengths and sized to the largest required scratch. This can be worked around of course by slicing to the correct length, however I think it would be more ergonomic if this was moved inside the library. Are you open to these checks be changed to the form of:
`assert!(scratch.len() >= self.get_scratch_len())`
or
`let scratch = &mut scratch[..self.get_scratch_len()]`
depending on whether there is a need for a slice of exact length?

**Comment by ejmahler** [comment]
Yes, I think that's a good idea.

**Comment by ejmahler** [comment]
Fixed in version 0.7. Thanks for the suggestion.
